//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_PROJECT_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class be_projectEntities : DbContext
    {
        public be_projectEntities()
            : base("name=be_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblstream> tblstreams { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<jobapi> jobapis { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<tblstudent> tblstudents { get; set; }
        public virtual DbSet<DocFile> DocFiles { get; set; }
        public virtual DbSet<PdfFile> PdfFiles { get; set; }
        public virtual DbSet<PptFile> PptFiles { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<placementcompany> placementcompanies { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<placement> placements { get; set; }
    }
}
