//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_PROJECT_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class placementcompany
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Aadhar { get; set; }
        public string PAN { get; set; }
        public string Address { get; set; }
        public string FathersOccupation { get; set; }
        public decimal FamilyIncome { get; set; }
        public string Degree { get; set; }
        public string University { get; set; }
        public decimal CGPA { get; set; }
        public int Backlogs { get; set; }
        public string Skills { get; set; }
        public string Experience { get; set; }
        public string Resume { get; set; }
    }
}
