//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_PROJECT_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string gender { get; set; }
        public string student_code { get; set; }
        public string email_address { get; set; }
        public string mobile_number { get; set; }
        public Nullable<int> stream_id { get; set; }
        public string fees { get; set; }
        public string password { get; set; }
        public string profile_photo { get; set; }
    
        public virtual tblstream tblstream { get; set; }
    }
}
